controlaesadiacsa/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from restapp.api.router import router_posts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('panel.urls')),
    path('api/', include(router_posts.urls))
]

panel/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('test_favicon', views.home_view, name="homeFavicon"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('index_noautenticado', views.index_noautenticado,
         name="index_noautenticado"),
    path('', views.autenticacion, name="autenticacion"),
    path('signout', views.signout, name="signout"),
    path('home', views.index, name="index"),
    path('listar', views.listar, name="listar"),
    path('agregar', views.agregar, name="agregar"),
    path('actualizar/<codigo>', views.actualizar, name="actualizar"),
    path('eliminar/<codigo>', views.eliminar, name="eliminar"),
    path('livedata', views.livedata, name="livedata"),
    path('livedata/agregar', views.livedata_agregar, name="livedata_agregar"),
    path('livedata/eliminar', views.livedata_eliminar, name="livedata_eliminar"),
    path('livedata/llenar', views.livedata_llenar, name="livedata_llenar"),
    path('marcacion', views.marcacion, name="marcacion"),
    path('marcacion/agregar', views.marcacion_agregar, name="marcacion_agregar"),
    path('noregistrados', views.noregistrados, name="noregistrados"),
    path('registrarusuario', views.registrarusuario, name="registrarusuario"),
    path('reset-password/<str:uidb64>/<str:token>/',
         views.reset_password, name='reset_password'),
    path('eliminarusuario', views.eliminarusuario, name="eliminarusuario"),
]

panel/models.py
from django.db import models
from django.contrib.auth.models import User

class PersonalRegistrado(models.Model):
    id = models.BigAutoField(primary_key=True)
    n_persona = models.CharField(max_length=8, null=False)
    ap_paterno = models.CharField(max_length=50, null=False)
    ap_materno = models.CharField(max_length=50, null=False)
    nombre = models.CharField(max_length=50, null=False)
    dni = models.CharField(max_length=8, null=False)
    f_nac = models.DateField(null=True)
    proyecto = models.CharField(max_length=50, null=False)
    centro_coste = models.CharField(max_length=50, null=False)
    tipo_trabajador = models.CharField(max_length=50, null=False)
    clave_sexo = models.CharField(max_length=1, null=False)
    f_alta = models.DateField(null=False)
    f_baja = models.DateField(null=True)
    motivo_cese = models.CharField(max_length=50, null=True)
    cargo = models.CharField(max_length=50, null=False)
    card_id = models.CharField(max_length=8, null=False)
    area = models.CharField(max_length=50, null=False)
    servicio = models.CharField(max_length=50, null=False)
    supervicion = models.CharField(max_length=50, null=False)
    guardia = models.CharField(max_length=1, null=False)
    correo = models.CharField(max_length=50, null=True)
    n_celular = models.CharField(max_length=50, null=True)

    class Meta:
        db_table = 'PersonalRegistrado'


class LiveData(models.Model):
    id = models.BigAutoField(primary_key=True)
    ubicacion = models.CharField(max_length=50, null=True)
    cardidHex = models.CharField(max_length=8, null=False)
    nombre = models.CharField(max_length=50, null=True)
    apellido = models.CharField(max_length=50, null=True)
    empresa = models.CharField(max_length=50, null=True)
    cargo = models.CharField(max_length=50, null=True)
    f_ingreso = models.DateField(null=True)
    h_ingreso = models.TimeField(null=True)

    def __str__(self):
        return str(self.cardidHex)+" "+str(self.ubicacion)

    class Meta:
        db_table = 'LiveData'


class Historial(models.Model):
    id = models.BigAutoField(primary_key=True)
    ubicacion = models.CharField(max_length=50, null=True)
    cardidHex = models.CharField(max_length=8, null=False)
    nombre = models.CharField(max_length=50, null=True)
    apellido = models.CharField(max_length=50, null=True)
    empresa = models.CharField(max_length=50, null=True)
    cargo = models.CharField(max_length=50, null=True)
    f_evento = models.DateField(null=True)
    h_evento = models.TimeField(null=True)
    evento = models.CharField(max_length=50, null=True)
    status = models.CharField(max_length=2, null=False, default='0')

    def __str__(self):
        return str(self.cardidHex)+" "+str(self.ubicacion)

    class Meta:
        db_table = 'Historial'


class NoRegistrados(models.Model):
    id = models.BigAutoField(primary_key=True)
    ubicacion = models.CharField(max_length=50, null=True)
    cardidHex = models.CharField(max_length=8, null=True)
    f_evento = models.DateField(null=True)
    h_evento = models.TimeField(null=True)
    evento = models.CharField(max_length=50, null=True)

    def __str__(self):
        return str(self.cardidHex)+" "+str(self.ubicacion)

    class Meta:
        db_table = 'NoRegistrados'


class deviceID(models.Model):
    id = models.IntegerField(primary_key=True)
    deviceID = models.CharField(max_length=8, null=True)
    ubicacion = models.CharField(max_length=50, null=True)

    def __str__(self):
        return str(self.deviceID)+" "+str(self.ubicacion)

    class Meta:
        db_table = 'deviceID'


class UserInfo(models.Model):
    User = models.OneToOneField(User, on_delete=models.CASCADE)
    DNI = models.CharField(max_length=8)
    Telefono = models.CharField(max_length=9)
    SegundoApellido = models.CharField(max_length=50)


#######################

panel/views.py
from django.core import serializers
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.http import JsonResponse

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth import get_user_model
from django.utils.encoding import force_str

from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes

from . import models

# from datetime import datetime
from django.utils import timezone
from django.utils.timezone import activate
import pytz

from django.db.models import Q

from . import Funciones as Fun
from .Funciones import debugPrint
from django.core.exceptions import ObjectDoesNotExist

import re
import random
import string
from datetime import datetime
import traceback
import openpyxl

from random import randrange
import json

# Create your views here.
TEMPLATE_DIRS = (
    'os.path.join(BASE_DIR, "templates")'
)

@login_required(login_url='autenticacion')
def dashboard(request):
    debugPrint("Ingreso a dashboard")
    X_var = 'Personal'
    Y_var = 'Ingreso/Salidas'
    #Color_var = {role: 'style'}
    #values = [[X_var, Y_var]]
    #debugPrint(models.LiveData.objects.count())
    values=[["PERSONAL QUE INGRESO",models.LiveData.objects.count(),'red']]
    values.append(["PERSONAL QUE SALIO",randrange(100),'blue'])
    values_JSON = json.dumps(values)
    return render(request, "dashboard/dashboard.html", {'values':values_JSON})

def home_view(request: HttpRequest) -> HttpResponse:
    return render(request, 'home.html')


def index_noautenticado(request):

    return render(request, "index.html")


def autenticacion(request):
    if request.method == "POST":

        if request.POST.get("Comando") == "VerificarLogin":
            Usuario = request.POST.get("Usuario")
            Contrasena = request.POST.get("Contrasena")
            Captcha = request.POST.get("Captcha")
            FormatoValido, Mensaje = Fun.FormatoLoginValidos(
                Usuario, Contrasena, Captcha)
            if not FormatoValido:
                return JsonResponse({"Estado": "Invalido", 'Mensaje': Mensaje})
            DatosValidos, Mensaje = Fun.DatosLoginValidos(
                request, Usuario, Contrasena)
            if DatosValidos:
                Correo = Fun.EnviarToken(Usuario, Contrasena, request)
                return JsonResponse({"Estado": "Valido", 'Mensaje': Mensaje, "Correo": Correo})
            return JsonResponse({"Estado": "Invalido", 'Mensaje': Mensaje})

        elif request.POST.get("Comando") == "VerificarToken":
            Usuario = request.POST.get("Usuario")
            Contrasena = request.POST.get("Contrasena")
            Token = request.POST.get("Token")
            if len(Token) != 6:
                return JsonResponse({"Estado": "Invalido", "Mensaje": "El Token debe ser de 8 digitos"})
            if not Fun.VerificarToken(Token):
                return JsonResponse({"Estado": "Invalido", 'Mensaje': "El token ingresado no es correcto"})
            DatosValidos, Mensaje = Fun.DatosLoginValidos(
                request, Usuario, Contrasena)
            if not DatosValidos:
                return JsonResponse({"Estado": "Invalido", 'Mensaje': "No deberias poder ver esto"})
            login(request, authenticate(
                request, username=Usuario, password=Contrasena))
            return JsonResponse({"Estado": "Valido", "Mensaje": "El token ha sido validado correctamente"})

        elif request.POST.get("Comando") == "RecuperarCuenta":
            Correo = request.POST.get("Correo")
            if len(Correo) == 0:
                return JsonResponse({"Estado": "Invalido", "Mensaje": "Debe ingresar su correo electronico"})
            try:
                Usuario = User.objects.get(email=Correo)
            except ObjectDoesNotExist:
                return JsonResponse({"Estado": "Invalido", "Mensaje": "El correo ingresado no se encuentra registrado"})
            token = default_token_generator.make_token(Usuario)
            uid = urlsafe_base64_encode(force_bytes(Usuario.pk))
            current_site = get_current_site(request)
            Asunto = 'Recuperar contraseña - DIACSA'
            reset_url = f"https://{current_site}/reset-password/{uid}/{token}/"
            MensajeHTML = f"""\
            <html>
            <head></head>
            <body>
                <p>Hola, <span style="font-size: larger;">{Usuario.first_name}</span>!</p>
                <p>Entra a este enlace para recuperar tu contraseña: <br><span style="font-size: larger;"><b>{reset_url}</b></span></p>
            </body>
            </html>
            """
            Fun.EnviaCorreo(Usuario.email, Asunto, MensajeHTML)
            return JsonResponse({"Estado": "Valido", "Mensaje": "El enlace de recuperacion ha sido enviado a su correo"})

        else:
            return JsonResponse({"Estado": "Invalido", 'Mensaje': "El comando es desconocido"})

    signout(request)
    return render(request, "login.html")


def reset_password(request, uidb64, token):
    if request.method == 'POST':
        try:
            UID = force_str(urlsafe_base64_decode(uidb64))
            Usuario = User.objects.get(pk=UID)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            Usuario = None
        if Usuario is None or not default_token_generator.check_token(Usuario, token):
            return JsonResponse({"Estado": "Invalido", "Mensaje": "El enlace de recuperacion no es valido"})
        NuevaContrasena = request.POST.get('Contrasena1')
        ConfirmacionContrasena = request.POST.get('Contrasena2')
        if NuevaContrasena != ConfirmacionContrasena:
            return JsonResponse({"Estado": "Invalido", "Mensaje": "Las contraseñas ingresadas no coinciden"})
        if not Fun.ContrasenaEsFuerte(NuevaContrasena):
            return JsonResponse({"Estado": "Invalido", "Mensaje": "La nueva contraseña debe tener:\nUna mayuscula.\nUna minuscula.\nSin numeros consecutivos.\nMinimo 8 caracteres"})
        Usuario.set_password(NuevaContrasena)
        Usuario.save()
        return JsonResponse({"Estado": "Valido", "Mensaje": "La contraseña se ha cambiado correctamente"})
    else:
        return render(request, 'reset_password.html')


@login_required(login_url='autenticacion')
def signout(request):
    logout(request)
    return redirect("autenticacion")


@login_required(login_url='autenticacion')
def index(request):
    debugPrint("Ingreso a intentar leer el livedata")
    users = models.LiveData.objects.all()
    data = {'total': users.count()}
    return render(request, "index.html", data)


@login_required(login_url='autenticacion')
def listar(request):
    if request.method == "POST" and request.user.is_superuser and (request.POST.get("Comando") == "Agregar"):
        debugPrint("Entra a Agregar Plantilla por excel")
        header = ["N° PERSONA", "APELLIDO PATERNO", "APELLIDO MATERNO", "NOMBRE", "DNI", "FECHA DE NACIMIENTO", "PROYECTO", "CENTRO DE COSTE", "TIPO DE TRABAJADOR",
                  "CLAVE DE SEXO", "FECHA DE ALTA", "FECHA DE BAJA", "MOTIVO DE CESE", "CARGO", "CÓDIGO DE TARJETA", "ÁREA", "SERVICIO", "SUPERVISIÓN", "GUARDIA", "CORREO", "N° CELULAR"]
        n_columnas = len(header)
        ExcelFile = request.FILES.get("excelFile")
        if not ExcelFile:
            return JsonResponse({'Estado': 'Invalido', 'Mensaje': "No se ha podido leer el archivo"})
        try:
            Excel = openpyxl.load_workbook(
                ExcelFile, read_only=True, keep_vba=True, data_only=True, keep_links=False)
        except Exception as e:
            return JsonResponse({'Estado': 'Invalido', 'Mensaje': str(e) + "\n" + traceback.format_exc()})
        Hoja = Excel.active
        if not Hoja:
            return JsonResponse({'Estado': 'Invalido', 'Mensaje': "El archivo no tienen ninguna hoja"})
        FilasTotales = Hoja.max_row
        debugPrint("La integridad del archivo es correcta")
        for i in range(0, n_columnas):
            try:
                if not str(Hoja[1][i].value).strip() == header[i].strip():
                    debugPrint(
                        f"{Hoja[1][i].value} != {header[i]}")
                    return JsonResponse({'Mensaje': 'La cabecera es incorrecta (parcialmente)', 'Estado': "Invalido"})
            except:
                return JsonResponse({'Mensaje': 'La cabecera es incorrecta', 'Estado': "Invalido"})
            debugPrint(
                f"Cabecera {i}, correcta: {Hoja[1][i].value}")
        debugPrint("La cabecera es correcta")
        filasInvalidas = [0]
        for i in range(2, FilasTotales):
            Fila = Hoja[i]
            for i in range(0, n_columnas):
                debugPrint(f"{header[i]}: {Fila[i].value}")
            return JsonResponse({'Mensaje': 'Planilla actualizada correctamente', 'Estado': "Valido"})
        if request.method == "POST" and request.user.is_superuser and (request.POST.get("Comando") == "Agregar"):
            ExcelFile = request.FILES.get("excelFile")
            if ExcelFile:
                try:
                    Excel = openpyxl.load_workbook(
                        ExcelFile, read_only=True, keep_vba=True, data_only=True, keep_links=False)
                    Hoja = Excel.active
                    FilasTotales = Hoja.max_row
                    debugPrint("Llego a leer el excel, eliminar")
                    for i in range(0, n_columnas):
                        try:
                            if not str(Hoja[1][i].value).strip() == header[i].strip():

panel/templates/livedata/livedata.html
{% extends '../index_master.html' %}

{% block head %}
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/css/bootstrap.min.css"> -->
<!-- <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css"> -->
<!-- <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css"> -->
{% endblock%}

{% block content %}
<form id="livedataForm" action="{%url 'livedata' %}" method="POST">
  {% csrf_token %}
  <div class="right_col" role="main">
    <h1 style="display: inline-block;">Lista de Personal al Interior de la Mina</h1>
    <div class="row" style="float: right;">
      <div class="tile_count">
        <div class="col-md-12 col-sm-12  tile_stats_count">
          <span class="count_top"><i class="fa fa-user"></i> Total de personal en mina</span>
          <div class="count" id="total">{{total}}</div>
        </div>
      </div>
    </div>
    <h2> Última actualización:</h2>
    <h2 id="ultimaactualizacion">{{fecha_y_hora|date:"j-m-Y H:i:s"}}</h2>


    <div class="table-responsive">
      <table id="DataLive" class="table table-striped table-hover table-secondary ">
        <thead>
          <tr>
            <th scope="col" data-bs-column-filter>#</th>
            <th scope="col" data-bs-column-filter>Ubicacion</th>
            <th scope="col" data-bs-column-filter>CardID</th>
            <th scope="col" data-bs-column-filter>Nombre</th>
            <th scope="col" data-bs-column-filter>Apellido</th>
            <th scope="col" data-bs-column-filter>Empresa</th>
            <th scope="col" data-bs-column-filter>Cargo</th>
            <th scope="col" data-bs-column-filter>Fecha de Ingreso</th>
            <th scope="col" data-bs-column-filter>Hora de Ingreso</th>
          </tr>
        </thead>
        <tbody>

          <!-- {% for u in livedata %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ u.ubicacion}}</td>
            <td>{{ u.cardidHex}}</td>
            <td>{{ u.nombre}}</td>
            <td>{{ u.apellido}}</td>
            <td>{{ u.empresa}}</td>
            <td>{{ u.cargo}}</td>
            <td>{{ u.f_ingreso}}</td>
            <td>{{ u.h_ingreso}}</td>
          </tr>
          {% endfor %} -->
        </tbody>

      </table>
    </div>
    {% if perms.panel.change_livedata %}
    <!-- <a href="livedata/agregar" class="btn btn-primary">Ingresar livedata</a>
    <a href="livedata/eliminar" class="btn btn-danger">Eliminar livedata</a> -->
    {% endif %}
  </div>
</form>
{% endblock%}

{% block scripts %}
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
{%load static%}
<script src="{%static 'livedata.js'%}"></script>
{% endblock %}

panel/templates/livedata/livedata_agregar.html
{% extends '../index_master.html' %}

{% block content %}
<div class="right_col" role="main">
  {%if r2%}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>r2</strong> Revise todos los campos.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  <h1>Agregar Livedata</h1>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group row">
      <label for="cardid" class="col-4 col-form-label">Card ID</label>
      <div class="col-8">
        <div class="input-group">
          <div class="input-group-addon">
            <i class="fas fa-credit-card"></i>
          </div>
          <input id="cardid" name="cardid" placeholder="Card Id" type="text" required="required" class="form-control"
            onchange="BusquedaDatos()">
        </div>
      </div>
    </div>

    <div class="form-group row">
      <label for="ubicacion" class="col-4 col-form-label">Ubicacion</label>
      <div class="col-8">
        <div class="input-group">
          <div class="input-group-addon">
            <i class="fas fa-map-marked"></i>
          </div>
          <input id="ubicacion" name="ubicacion" placeholder="Ubicacion" type="text" required="required"
            class="form-control">
        </div>
      </div>
    </div>

    <div class="form-group row">
      <label for="nombre" class="col-4 col-form-label">Nombre</label>
      <div class="col-8">
        <div class="input-group">
          <div class="input-group-addon">
            <i class="fas fa-user"></i>
          </div>
          <input id="nombre" name="nombre" placeholder="Nombre" type="text" required="required" class="form-control">
        </div>
      </div>
    </div>
    <div class="form-group row">
      <label for="apellido" class="col-4 col-form-label">Apellido</label>
      <div class="col-8">
        <div class="input-group">
          <div class="input-group-addon">
            <i class="fas fa-user"></i>
          </div>
          <input id="apellido" name="apellido" placeholder="Apellido" type="text" class="form-control">
        </div>
      </div>
    </div>
    <div class="form-group row">
      <label for="cargo" class="col-4 col-form-label">Cargo</label>
      <div class="col-8">
        <div class="input-group">
          <div class="input-group-addon">
            <i class="fas fa-user-tag"></i>
          </div>
          <input id="cargo" name="cargo" placeholder="Cargo" type="text" class="form-control">
        </div>
      </div>
    </div>
    <div class="form-group row">
      <label for="fnac" class="col-4 col-form-label">Fecha de Ingreso</label>
      <div class="col-8">
        <div class="input-group">
          <div class="input-group-addon">
            <i class="fas fa-calendar"></i>
          </div>
          <input id="f_ingreso" name="f_ingreso" placeholder="Fecha de ingreso" type="date" required="required"
            class="form-control">
        </div>
      </div>
    </div>
    <div class="form-group row">
      <label for="fnac" class="col-4 col-form-label">Hora de Ingreso</label>
      <div class="col-8">
        <div class="input-group">
          <div class="input-group-addon">
            <i class="fas fa-clock"></i>
          </div>
          <input id="h_ingreso" name="h_ingreso" placeholder="Hora de ingreso" type="time" required="required"
            class="form-control">
        </div>
      </div>
    </div>
    <div class="form-group row">
      <div class="offset-4 col-8">
        <button name="submit" type="button" onclick="AgregarDatos()" class="btn btn-primary"><i
            class="fa fa-user-plus"></i> Agregar
          Livedata</button>
      </div>
    </div>
  </form>
</div>
{% endblock%}

panel/templates/livedata/livedata_eliminar.html
{% extends '../index_master.html' %}

{% block content %}
<div class="right_col" role="main">
    <h1>Eliminar Livedata</h1>

    <form action="eliminar" method="POST">
        {% csrf_token %}
        <div class="form-group row">
            <label for="id" class="col-4 col-form-label">CardID Personal Livedata</label>
            <div class="col-8">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-list-ol"></i>
                    </div>
                    <select id="cardidHex" name="cardidHex" class="form-control" onchange="ObtenerDatosCardID()">
                        <option value="--------">--------</option>
                        {% for u in livedata %}
                        <option value="{{u.cardidHex}}">{{u.cardidHex}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label for="ubicacion" class="col-4 col-form-label">Ubicacion</label>
            <div class="col-8">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fas fa-map-marked"></i>
                    </div>
                    <input id="ubicacion" name="informacion" placeholder="Ubicacion" type="text" required="required"
                        class="form-control" disabled>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="nombre" class="col-4 col-form-label">Nombre</label>
            <div class="col-8">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fas fa-user"></i>
                    </div>
                    <input id="nombre" name="informacion" placeholder="Nombre" type="text" required="required"
                        class="form-control" disabled>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="apellido" class="col-4 col-form-label">Apellido</label>
            <div class="col-8">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fas fa-user"></i>
                    </div>
                    <input id="apellido" name="informacion" placeholder="Apellido" type="text" class="form-control"
                        disabled>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="cargo" class="col-4 col-form-label">Cargo</label>
            <div class="col-8">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fas fa-user-tag"></i>
                    </div>
                    <input id="cargo" name="informacion" placeholder="Cargo" type="text" class="form-control" disabled>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="fnac" class="col-4 col-form-label">Fecha de Ingreso</label>
            <div class="col-8">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fas fa-calendar"></i>
                    </div>
                    <input id="f_ingreso" name="informacion" placeholder="Fecha de ingreso" type="text"
                        required="required" class="form-control" disabled>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label for="fnac" class="col-4 col-form-label">Hora de Ingreso</label>
            <div class="col-8">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fas fa-clock"></i>
                    </div>
                    <input id="h_ingreso" name="informacion" placeholder="Hora de ingreso" type="text"
                        required="required" class="form-control" disabled>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-4 col-8">
                <button name="eliminar" type="button" class="btn btn-danger" onclick="EliminarLivedata()"><i
                        class="fa fa-user-times"></i>&nbsp;&nbsp;Eliminar
                    Livedata</button>
            </div>
        </div>
    </form>
</div>
{% endblock%}